### ISSUE TITLE
Feature Request: starting casa-corrently behind a webproxy

### ISSUE THREAD

**Issue by clehne** [energychain/casa-corrently#5]
I want to redirect the output of casa corrently through a nginx proxy within a location url of e.g. /my-personal-electricity-costs.  
The app does not work when going through the nginx proxy. 
What I miss is a build or start option for casa-corrently to tell it the base-href.

**Comment by zoernert** [comment]
newest casa-corrently-webinterface should have all relevant values with valid base paths. However I think the issue is in the version that is included in current influx version.

**Comment by zoernert** [comment]
Implemented as of Release: https://github.com/energychain/casa-corrently/releases/tag/v1.0.46
